[tools]
dotnet = "9"
python = "3.13"
"pipx:gitingest" = { version = "latest" }
"pipx:pre-commit" = { version = "latest" }

[settings]
python.uv_venv_auto = true

[tasks.build]
alias = "build"
description = "Build the solution."
run = ["dotnet build Night.sln"]

[tasks.digest]
alias = "digest"
description = "Run gitingest on current directory."
run = [
  "gitingest -o project/digest.txt -e *.toml,*.txt,.roo/*,.cursor/*,build/*,.devenv/*,.direnv/*,project/digest.txt,project/archive/*,*.lock,bin/*,obj/*,lib/*,.venv/*,.windsurf/*,src/SampleGame/bin/*,src/Night/bin/*,src/SampleGame/obj/*,src/Night/obj/*,site/_site/*,site/api/*,tests/Night.Tests/bin/*,tests/Night.Tests/obj/* .",
]

[tasks.game]
alias = "game"
description = "Run the sample game."
run = ["dotnet run --project src/SampleGame/SampleGame.csproj"]

[tasks.test]
alias = "test"
description = "Run automated tests"
run = ["SDL_VIDEODRIVER=dummy dotnet test --filter TestType=Automated"]
run_windows = ["dotnet test --filter TestType=Automated"]

[tasks.manual-test]
alias = "man-test"
description = "Run manual tests"
run = ["dotnet test --filter TestType=Manual"]

[tasks.clean]
alias = "clean"
description = "Clean bin and obj directories."
run = ["dotnet clean Night.sln"]

[tasks.sdl]
description = "Update SDL bindings and sync SDL libs."
run = [
  "git submodule update --remote lib/SDL3-CS",
  "python scripts/sync_sdl3.py",
]

[tasks.tools]
description = "Update tools."
run = [
  "git submodule update --remote lib/SDL3-CS",
  "python scripts/update_tools.py",
]

[tasks.update-api-doc]
description = "Update API docs."
run = ["python scripts/update_api_doc.py"]

[tasks.prepare]
alias = "prepare"
description = "Prepare everything before a commit."
run = [
  "dotnet clean Night.sln",
  "dotnet tool restore",
  "dotnet format --verbosity diagnostic Night.sln",
  "dotnet build Night.sln",
  "SDL_VIDEODRIVER=dummy dotnet test --filter TestType=Automated",
  "dotnet docfx docs/docfx.json",
  "python scripts/update_api_doc.py",
]
run_windows = [
  "dotnet clean Night.sln",
  "dotnet tool restore",
  "dotnet format --verbosity diagnostic Night.sln",
  "dotnet build Night.sln",
  "dotnet test --filter TestType=Automated",
  "dotnet docfx docs/docfx.json",
  "python scripts/update_api_doc.py",
]

[tasks.docs]
alias = "docs"
description = "Generate docs."
run = ["dotnet docfx docs/docfx.json"]

[tasks.format]
alias = "format"
description = "Format files."
run = ["dotnet format --verbosity verbose Night.sln"]
